name: .NET Core API App

on:
    workflow_dispatch:
      
# on: [push, pull_request, workflow_dispatch]
#     push:
#     branches:
#       - master

jobs:
    build:
        runs-on: ${{ matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: 8.0.x #${{ matrix.dotnet-version }}

        - name: Install/Restore Dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --no-restore

        - name: Test with dotnet CLI
          run: dotnet test --no-build

        - name: Publish artifact
          run: dotnet publish --output ./artifacts

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: drop-artifacts-${{ matrix.os }} # if job runs on two different runners, the artifacts will be named differently or name conflict will occur 
            path: ./artifacts
          
    docker-build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
        
        steps:
          


# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest]

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Setup .NET Core
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: '7.0.x' # Adjust the version as needed

#     - name: Restore dependencies
#       run: dotnet restore

#     - name: Build
#       run: dotnet build --no-restore --configuration Release

#     - name: Run tests
#       run: dotnet test --no-build --verbosity normal
